/* 
File: home.tsx
Function: This is the Home screen component for the app where the recommendations generated by the AI engine will display.
*/

import React, { useState, useRef, useEffect } from 'react';
import { View, ScrollView, ActivityIndicator, SafeAreaView } from 'react-native';
import { Text, Button, Card} from 'react-native-paper';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { styles } from './app_styles.styles';
import { Animated, Easing } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';


// Define the navigation parameter list
export type RootParamList = {
  Home: undefined;
};

// Define the type for Home screen navigation prop
type HomeScreenProp = NativeStackNavigationProp<RootParamList, 'Home'>;

// Cute spinning globe loader
const GlobeLoader = () => {
  const spinAnim = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    const loop = Animated.loop(
      Animated.timing(spinAnim, {
        toValue: 1,
        duration: 1200,
        easing: Easing.linear,
        useNativeDriver: true,
      })
    );
    loop.start();
    return () => loop.stop();
  }, [spinAnim]);

  const spin = spinAnim.interpolate({
    inputRange: [0, 1],
    outputRange: ['0deg', '360deg'],
  });

  return (
    <View style={styles.globeLoaderContainer}>
      <Animated.View style={{ transform: [{ rotate: spin }] }}>
        <MaterialCommunityIcons name="earth" size={40} color="#6540D8" />
      </Animated.View>
    </View>
  );
};


// Home component
const Home = () => {
  // Initialize navigation with type safety
  const navigation = useNavigation<HomeScreenProp>();
  const [loading, setLoading] = useState(false);
  const [recommendations, setRecommendations] = useState<any[]>([]);
  const [labelMappings, setLabelMappings] = useState<Record<string, string[]>>({});
  const [vacationTypes, setVacationTypes] = useState<string[]>([]);

  // Fetch label mappings dynamically from backend
  useEffect(() => {
    const loadMappings = async () => {
      try {
        const response = await fetch('https://capstone-team-generated-group30-project.onrender.com/metadata');
        const data = await response.json();
        setLabelMappings(data.label_mappings);
        setVacationTypes(data.vacation_types);
      } catch (err) {
        console.error('Error loading label mappings:', err);
      }
    };
    loadMappings();
  }, []);

  // Encoding function
  const encodeUserInput = (userInput: Record<string, string>) => {
    const categoricalFeatures = [
      'origin_country',
      'seasons',
      'budget',
      'favorite_country_visited',
      'travel_distance',
      'place_type',
    ];

    //This encodes it into categorical features
    const userCatEncoded = categoricalFeatures.map((feature) => {
      const classes = labelMappings[feature];
      const value = userInput[feature] ?? '';
      if (classes && classes.includes(value)) {
        return classes.indexOf(value);
      } else {
        console.warn(`Unseen label '${value}' for feature '${feature}'`);
        return -1;
      }
    });

    //This encodes the vacation features
    const userVacationEncoded = new Array(vacationTypes.length).fill(0);
    if (userInput.vacation_types) {
      const vacationList = userInput.vacation_types.split('|');
      vacationList.forEach((vt) => {
        const idx = vacationTypes.indexOf(vt);
        if (idx >= 0) userVacationEncoded[idx] = 1;
      });
    }

    return { categorical: userCatEncoded, vacationTypes: userVacationEncoded };
  };

  // Create fake users for testing
  const fakeUsers = [
    {
      name: 'Budget Backpacker',
      origin_country: 'Mexico',
      seasons: 'Summer',
      budget: 'Low',
      favorite_country_visited: 'USA',
      travel_distance: 'Medium',
      place_type: 'City',
      vacation_types: 'Adventure|Nature',
    },
    {
      name: 'Luxury Traveler',
      origin_country: 'Germany',
      seasons: 'Winter',
      budget: 'High',
      favorite_country_visited: 'France',
      travel_distance: 'Long',
      place_type: 'Beach',
      vacation_types: 'Relaxation|Culture|Shopping',
    },
    {
      name: 'Nature Lover',
      origin_country: 'Canada',
      seasons: 'Spring',
      budget: 'Mid',
      favorite_country_visited: 'Japan',
      travel_distance: 'Long',
      place_type: 'Mountains',
      vacation_types: 'Adventure|Nature|Relaxation',
    },
  ];

  // Pick one fake user for demonstration
  const userInput = fakeUsers[2]; // Change index to test different users
  // This function calls to the API with the tokenized user input to get the recommendations.
  const fetchRecommendations = async () => {
    
    if (!Object.keys(labelMappings).length) {
      console.error('Encoders not loaded yet');
      return;
    }
    
    setLoading(true); // Show a loading screen waiting for the recommendations.
    try { // First, we will fetch the recommendations hosted page and then post the vectorized input data for the specific user.
      const encoded = encodeUserInput(userInput);
      const queryVector = [...encoded.categorical, ...encoded.vacationTypes];

      const response = await fetch('https://capstone-team-generated-group30-project.onrender.com/recommend', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ query_vector: queryVector })
      });

      const data = await response.json(); // Once we have given the data, it will run the hosted app.py to generate recommendations from the model.
      setRecommendations(data.recommendations || []); // Get the recommendations, otherwise return empty.
    } catch (error) {
      console.error('Error fetching recommendations:', error);
    } finally {
      setLoading(false); // Once recommendations are received, we can stop the loading screen.
    }
  };

  return (
    <SafeAreaView style={styles.safeArea}>
      <ScrollView contentContainerStyle={styles.homeContainer}>
        
        {/* Title */}
        <Text variant="headlineLarge" style={styles.homeTitle}>
          Your Adventure{'\n'}Starts Here!
        </Text>
  
        {/* Button */}
        <Button
          mode="contained"
          onPress={fetchRecommendations}
          style={styles.recommendButton}
          labelStyle={styles.recommendButtonLabel}
        >
          Get Recommendations
        </Button>
  
        {loading && <GlobeLoader />}
  
        {/* Recommendations */}
        {recommendations.length > 0 && !loading && (
          <View style={styles.resultsContainer}>
            <Text style={styles.sectionTitle}>Top Cities:</Text>
  
            {recommendations.map((city) => (
              <Card key={city.city_id} style={styles.cityCard}>
                {/* Placeholder “image” block */}
                <View style={styles.cityImagePlaceholder} />
  
                {/* Text section */}
                <View style={styles.cityInfo}>
                  <Text style={styles.cityName}>
                    {city.city_name}, {city.country}
                  </Text>
                  <Text style={styles.cityScore}>
                    Score: {city.score.toFixed(2)}
                  </Text>
                </View>
              </Card>
            ))}
          </View>
        )}
  
      </ScrollView>
    </SafeAreaView>
  )};
export default Home;