/* 
File: home.tsx
Function: This is the Home screen component for the app that the recommendations generated by the AI engine.
*/

import { View } from 'react-native';
import { Text, } from 'react-native-paper';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { styles } from './app_styles.styles';

// Define the navigation parameter list
export type RootParamList = {
  Home: undefined;
};

// Define the type for Home screen navigation prop
type HomeScreenProp = NativeStackNavigationProp<RootParamList, 'Home'>;

// Home component
const Home = () => {
  // Initialize navigation with type safety
  const navigation = useNavigation<HomeScreenProp>();
  return (
    <View style={[styles.container, { flex: 1 }]}>
      <Text variant="headlineLarge" style={styles.title}>Your Adventure Starts Here!</Text>
    </View>
  );
}

export default Home;
