/* 
File: home.tsx
Function: This is the Home screen component for the app where the recommendations generated by the AI engine will display.
*/

import React, { useState, useRef, useEffect } from 'react';
import { View, ScrollView, ActivityIndicator, Image } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Text, Button, Card} from 'react-native-paper';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { styles } from './app_styles.styles';
import { Animated, Easing } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { getAuth } from 'firebase/auth';
import { doc, getDoc } from 'firebase/firestore';
import { FIREBASE_DB } from '../../FirebaseConfig';


// Define the navigation parameter list
export type RootParamList = {
  Home: undefined;
};
interface Recommendation {
  city_id: string;
  city_name: string;
  country: string;
  score: number;
  description?: string;
  image?: string;
}

// Define the type for Home screen navigation prop
type HomeScreenProp = NativeStackNavigationProp<RootParamList, 'Home'>;

// Cute spinning globe loader
const GlobeLoader = () => {
  const spinAnim = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    const loop = Animated.loop(
      Animated.timing(spinAnim, {
        toValue: 1,
        duration: 1200,
        easing: Easing.linear,
        useNativeDriver: true,
      })
    );
    loop.start();
    return () => loop.stop();
  }, [spinAnim]);

  const spin = spinAnim.interpolate({
    inputRange: [0, 1],
    outputRange: ['0deg', '360deg'],
  });

  return (
    <View style={styles.globeLoaderContainer}>
      <Animated.View style={{ transform: [{ rotate: spin }] }}>
        <MaterialCommunityIcons name="earth" size={40} color="#6540D8" />
      </Animated.View>
    </View>
  );
};


// Home component
const Home = () => {
  // Initialize navigation with type safety
  const navigation = useNavigation<HomeScreenProp>();
  const [loading, setLoading] = useState(false);
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [error, setError] = useState<string | null>(null);

  const fetchCityInfo = async (cityName: string, country: string) => {
    try {
      const query = `${cityName}, ${country}`;
      const url = `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(query)}`;

      const res = await fetch(url);
      const data = await res.json();

      return {
        description: data.extract || 'No description available.',
        image: data.thumbnail?.source || undefined,
      };
    } catch (err) {
      console.error('Error fetching city info:', err);
      return {
        description: 'No description available.',
        image: undefined,
      };
    }
  };

  // Load recommendations from Firestore
  useEffect(() => {
    const loadRecommendations = async () => {
      setLoading(true);
      try {
        const auth = getAuth();
        const user = auth.currentUser;
        if (!user) {
          setError('No user signed in.');
          setLoading(false);
          return;
        }

        const userRecRef = doc(FIREBASE_DB, 'userRec', user.uid);
        const snapshot = await getDoc(userRecRef);

        if (snapshot.exists()) {
          const data = snapshot.data();
          const recs: Recommendation[] = data.gen_recommendations || [];

          const enrichedRecs = await Promise.all(
            recs.map(async (city) => {
              const extra = await fetchCityInfo(city.city_name, city.country);
              return { ...city, ...extra };
            })
          );
          
          setRecommendations(enrichedRecs);
        } else {
          setError('No recommendations found. Please complete your profile setup.'); // Change to some loading screen
        }

      } catch (err) {
        console.error('Error loading recommendations:', err);
        setError('Failed to load recommendations.');
      } finally {
        setLoading(false);
      }
    };

    loadRecommendations();
  }, []);

  return (
    <SafeAreaView style={styles.safeArea}>
      <ScrollView contentContainerStyle={styles.homeContainer}>
        
        {/* Title */}
        <Text variant="headlineLarge" style={styles.homeTitle}>
          Your Adventure{'\n'}Starts Here!
        </Text>

        {/* Loading */}
        {loading && (
          <Text style={styles.sectionTitle}>Loading recommendations...</Text>
        )}

        {/* Error */}
        {error && !loading && (
          <Text>{error}</Text>
        )}

        {/* Recommendations */}
        {recommendations.length > 0 && !loading && (
          <View style={styles.resultsContainer}>
            <Text style={styles.sectionTitle}>Top Cities:</Text>
            
            {recommendations.map((city) => (
              <Card key={city.city_id} style={styles.cityCard}>
                {/* Inner wrapper handles rounding without clipping shadow */}
                <View style={styles.cityCardInner}>
                  {/* City image */}
                  {city.image ? (
                    <Image
                      source={{ uri: city.image }}
                      style={styles.cityImage}
                      resizeMode="cover"
                    />
                  ) : (
                    <View style={styles.cityImagePlaceholder} />
                  )}

                  {/* Text section */}
                  <View style={styles.cityInfo}>
                    <Text style={styles.cityName}>
                      {city.city_name}, {city.country}
                    </Text>
                  </View>
                </View>
              </Card>
            ))}

          </View>
        )}
      </ScrollView>
    </SafeAreaView>
  );
};
export default Home;