/* 
File: home.tsx
Function: This is the Home screen component for the app where the recommendations generated by the AI engine will display.
*/

import React, { useState, useRef, useEffect } from 'react';
import { View, ScrollView, ActivityIndicator, Image, Pressable, Modal, Dimensions } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Text, Button, Card} from 'react-native-paper';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { styles } from './app_styles.styles';
import { Animated, Easing } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { getAuth } from 'firebase/auth';
import { doc, getDoc } from 'firebase/firestore';
import { FIREBASE_DB } from '../../FirebaseConfig';


// Define the navigation parameter list
export type RootParamList = {
  Home: undefined;
  Recommendations: {recommendations: Recommendation[]};
  Liked: undefined;
};

interface Recommendation {
  city_id: string;
  city_name: string;
  country: string;
  score: number;
  description?: string;
  image?: string;
}

// Define the type for Home screen navigation prop
type RecommendationScreenProp = NativeStackNavigationProp<RootParamList, 'Recommendations'>;

// Cute spinning globe loader
const GlobeLoader = () => {
  const spinAnim = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    const loop = Animated.loop(
      Animated.timing(spinAnim, {
        toValue: 1,
        duration: 1200,
        easing: Easing.linear,
        useNativeDriver: true,
      })
    );
    loop.start();
    return () => loop.stop();
  }, [spinAnim]);

  const spin = spinAnim.interpolate({
    inputRange: [0, 1],
    outputRange: ['0deg', '360deg'],
  });

  return (
    <View style={styles.globeLoaderContainer}>
      <Animated.View style={{ transform: [{ rotate: spin }] }}>
        <MaterialCommunityIcons name="earth" size={40} color="#6540D8" />
      </Animated.View>
    </View>
  );
};


// Home component
const Recommendations = () => {
  // Initialize navigation with type safety
  const navigation = useNavigation<RecommendationScreenProp>();
  const [loading, setLoading] = useState(false);
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [selectedCity, setSelectedCity] = useState<Recommendation | null>(null);
  const [cityModalOpen, setCityModalOpen] = useState(false);


  const fetchWikivoyageIntro = async (
    cityName: string,
    country: string
  ): Promise<string | null> => {
    const titlesToTry = [
      cityName,
      `${cityName}, ${country}`,
      `${cityName} (${country})`,
    ];
  
    for (const title of titlesToTry) {
      try {
        const url =
          `https://en.wikivoyage.org/w/api.php` +
          `?action=query&format=json&origin=*` +
          `&prop=extracts&exintro=1&explaintext=1&redirects=1` +
          `&titles=${encodeURIComponent(title)}`;
  
        const res = await fetch(url);
        const data = await res.json();
  
        const pages = data?.query?.pages;
        if (!pages) continue;
  
        const page = pages[Object.keys(pages)[0]];
        const extract = page?.extract;
  
        if (
          extract &&
          !extract.toLowerCase().includes('more than one place') &&
          !extract.toLowerCase().includes('may refer to')
        ) {
          return extract;
        }
      } catch {
        continue;
      }
    }
  
    return null;
  };
  
  
  const shorten = (text: string, sentences = 3) => {
    const cleaned = text.replace(/\s+/g, ' ').trim();
    if (!cleaned) return '';
    const parts = cleaned.split('. ');
    const sliced = parts.slice(0, sentences).join('. ');
    return sliced.endsWith('.') ? sliced : sliced + '.';
  };
  
  const fetchWikipediaSummary = async (title: string) => {
    const url = `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(title)}`;
    const res = await fetch(url);
    if (!res.ok) return null;
    return res.json();
  };

  const isFlagImage = (url?: string) => {
    if (!url) return false;
    const lower = url.toLowerCase();
    return lower.includes('flag') || lower.includes('flag_of');
  };  
  
  const fetchCityInfo = async (cityName: string, country: string) => {
    try {
      // 1) Travel-style text first from Wikivoyage
      const voyText = await fetchWikivoyageIntro(cityName, country);
      // 2) Wikipedia fallback
      let wikiData = await fetchWikipediaSummary(cityName);
      if (!wikiData) {
        wikiData = await fetchWikipediaSummary(`${cityName}, ${country}`);
      }
  
      const wikiText: string | null = wikiData?.extract || null;
      const rawImage =
        wikiData?.originalimage?.source ||
        wikiData?.thumbnail?.source;
        
      const image = isFlagImage(rawImage) ? undefined : rawImage;
  
      const descriptionRaw = voyText || wikiText || '';
      const description = descriptionRaw
        ? shorten(descriptionRaw, 3)
        : 'No description available.';
  
      return { description, image };
    } catch (err) {
      console.error('Error fetching city info:', err);
      return { description: 'No description available.', image: undefined };
    }
  };  

  // Load recommendations from Firestore
  useEffect(() => {
    const loadRecommendations = async () => {
      setLoading(true);
      try {
        const auth = getAuth();
        const user = auth.currentUser;
        if (!user) {
          setError('No user signed in.');
          setLoading(false);
          return;
        }

        const userRecRef = doc(FIREBASE_DB, 'userRec', user.uid);
        const snapshot = await getDoc(userRecRef);

        if (snapshot.exists()) {
          const data = snapshot.data();
          const recs: Recommendation[] = data.gen_recommendations || [];

          const enrichedRecs = await Promise.all(
            recs.map(async (city) => {
              const extra = await fetchCityInfo(city.city_name, city.country);
              return { ...city, ...extra };
            })
          );
          
          setRecommendations(enrichedRecs);
        } else {
          setError('No recommendations found. Please complete your profile setup.'); // Change to some loading screen
        }

      } catch (err) {
        console.error('Error loading recommendations:', err);
        setError('Failed to load recommendations.');
      } finally {
        setLoading(false);
      }
    };

    loadRecommendations();
  }, []);

  return (
    <SafeAreaView style={styles.safeArea}>
      <ScrollView contentContainerStyle={styles.homeContainer}>
        
        {/* Title */}
        <Text variant="headlineLarge" style={styles.homeTitle}>
          Your Adventure{'\n'}Starts Here!
        </Text>

        {/* Loading */}
        {loading && (
          <Text style={styles.sectionTitle}>Loading recommendations...</Text>
        )}

        {/* Error */}
        {error && !loading && (
          <Text>{error}</Text>
        )}

        {/* Recommendations */}
        {recommendations.length > 0 && !loading && (
          <View style={styles.resultsContainer}>
            <Text style={styles.sectionTitle}>Top Cities:</Text>
            
            {recommendations.map((city) => (
              <Pressable
                key={city.city_id}
                onPress={() => {
                  setSelectedCity(city);
                  setCityModalOpen(true);
                }}
              >
                <Card style={styles.cityCard}>
                  <View style={styles.cityCardInner}>
                    {city.image ? (
                      <Image
                        source={{ uri: city.image }}
                        style={styles.cityImage}
                        resizeMode="cover"
                      />
                    ) : (
                      <View style={styles.cityImagePlaceholder} />
                    )}

                    <View style={styles.cityInfo}>
                      <Text style={styles.cityName}>
                        {city.city_name}, {city.country}
                      </Text>
                    </View>
                  </View>
                </Card>
              </Pressable>
            ))}


          </View>
        )}
      </ScrollView>
      <Modal
        visible={cityModalOpen}
        transparent
        animationType="slide"
        onRequestClose={() => setCityModalOpen(false)}
      >
        {/* dark background overlay */}
        <Pressable
          style={{
            flex: 1,
            backgroundColor: 'rgba(0,0,0,0.4)',
            justifyContent: 'center',
          }}
          onPress={() => setCityModalOpen(false)}
        >
          {/* modal card (stops closing when you tap inside) */}
          <Pressable style={styles.cityModalContainer}>
            {selectedCity && (
              <View>
                <Text style={styles.cityModalTitle}>
                  {selectedCity.city_name}, {selectedCity.country}
                </Text>

                {selectedCity.image ? (
                  <Image
                    source={{ uri: selectedCity.image }}
                    style={styles.cityModalImage}
                    resizeMode="cover"
                  />
                ) : null}

                <Text style={styles.cityModalDescription}>
                  {selectedCity.description || 'No description available.'}
                </Text>

                <Button
                  mode="contained"
                  onPress={() => setCityModalOpen(false)}
                  style={styles.cityModalCloseBtn}
                >
                  Close
                </Button>
              </View>
            )}
          </Pressable>
        </Pressable>
      </Modal>


    </SafeAreaView>
  );
};
export default Recommendations;